
CREATE TABLE chromosomes (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  chr VARCHAR(12) NOT NULL,
  prob DECIMAL(6,5) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE breakpoints (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  chr VARCHAR(12) NOT NULL,
  band VARCHAR(12) NOT NULL,
  bp_prob DECIMAL(6,5) NOT NULL,
  per_chr_prob DECIMAL(6,5) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE aneuploidy (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  chr VARCHAR(12) NOT NULL,
  prob DECIMAL(6,5) NOT NULL,
  gain DECIMAL(6,5) NOT NULL,
  loss DECIMAL(6,5) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE karyotype_probabilities (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  prob_type VARCHAR(12) CONSTRAINT type_ck CHECK (prob_type IN ('aberration', 'aneuploidy', 'breakpoint', 'chromosome')) NOT NULL,
  min_count INT NOT NULL,
  max_count INT NOT NULL,
  prob DECIMAL(6,5) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE chromosome_bands (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  chr VARCHAR(12) NOT NULL,
  band VARCHAR(12) NOT NULL,
  start_loc INT NOT NULL,
  end_loc INT NOT NULL,
  PRIMARY KEY (id)
);

