#!/bin/sh

## Normal text file generated by get_normal_stats.R

if [ $# -lt 2 ]; then
  echo "Usage: $0 <normal text file> <list of directories with bam files, space separated>"
  exit
fi

normal=$1
dirlist=${@:2}

echo ${dirlist[@]}

for dir in ${dirlist[@]}
do
    if [ -e $dir/paired_reads.txt ]; then
        echo "$dir/paired_reads.txt exists"
    else
        echo "run read_alignments.R Rscript on $dir"
        Rscript read_alignments.R $dir $normal
    fi

    if [ -e $dir/summary.Rdata ]; then
      echo "dir/summary.Rdata exists"
    else
        echo "score $dir"
        Rscript read_distance_analysis.R $dir $normal T
    fi

    if [ -e $dir/paired_reads.txt ] & [ -e $dir/summary.Rdata ]; then
        `rm $dir/*.bam*`
    fi

done


